---
- name: Get Started
  hosts: all

  tasks:
          - name: Upgrade all apt packages
            apt:
                    force_apt_get: yes
                    upgrade: dist
            become: yes

          - name: Check uptime
            register: uptimeoutput
            command: "uptime"

          - name: Check hostname, version, and distribution
            register: unameout
            command: "uname -a"

          - name: Check disk usage
            register: dfout
            command: "df -h"
